"use client";
// import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/lib/components/layout";
import localFont from "next/font/local";
import { heebo, nunito, poppins } from "@theme/fonts";
import Popup from "@/lib/hook/Context/popup";

// export const metadata: Metadata = {
//   title: "MeoApp",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
      // className={`${poppins.variable} ${nunito.variable} ${heebo.variable}`}
      >
        <Popup>
          <NavBar>{children}</NavBar>
        </Popup>
      </body>
    </html>
  );
}
