const tracks = [
  {
    id: "1",
    title: "Ukulele",
    artist: "Bensound",
    src: "https://www.bensound.com/bensound-music/bensound-ukulele.mp3",
    cover: "https://www.bensound.com/bensound-img/ukulele.jpg",
  },
  {
    id: "2",
    title: "Summer",
    artist: "Bensound",
    src: "https://www.bensound.com/bensound-music/bensound-summer.mp3",
    cover: "https://www.bensound.com/bensound-img/summer.jpg",
  },
  {
    id: "3",
    title: "Happy Rock",
    artist: "Bensound",
    src: "https://www.bensound.com/bensound-music/bensound-happyrock.mp3",
    cover: "https://www.bensound.com/bensound-img/happyrock.jpg",
  },
  {
    id: "4",
    title: "Jazzy Frenchy",
    artist: "Bensound",
    src: "https://www.bensound.com/bensound-music/bensound-jazzyfrenchy.mp3",
    cover: "https://www.bensound.com/bensound-img/jazzyfrenchy.jpg",
  },
  {
    id: "5",
    title: "Acoustic Breeze",
    artist: "Bensound",
    src: "https://www.bensound.com/bensound-music/bensound-acousticbreeze.mp3",
    cover: "https://www.bensound.com/bensound-img/acousticbreeze.jpg",
  },
  {
    id: "6",
    title: "Punky",
    artist: "Bensound",
    src: "https://www.bensound.com/bensound-music/bensound-punky.mp3",
    cover: "https://www.bensound.com/bensound-img/punky.jpg",
  },
  {
    id: "7",
    title: "Badass",
    artist: "Bensound",
    src: "https://www.bensound.com/bensound-music/bensound-badass.mp3",
    cover: "https://www.bensound.com/bensound-img/badass.jpg",
  },
  {
    id: "8",
    title: "Brazil Samba",
    artist: "Bensound",
    src: "https://www.bensound.com/bensound-music/bensound-brazilsamba.mp3",
    cover: "https://www.bensound.com/bensound-img/brazilsamba.jpg",
  },
  {
    id: "9",
    title: "Creepy",
    artist: "Bensound",
    src: "https://www.bensound.com/bensound-music/bensound-creepy.mp3",
    cover: "https://www.bensound.com/bensound-img/creepy.jpg",
  },
  {
    id: "10",
    title: "High Octane",
    artist: "Bensound",
    src: "https://www.bensound.com/bensound-music/bensound-highoctane.mp3",
    cover: "https://www.bensound.com/bensound-img/highoctane.jpg",
  },
];
